[project]
name = "bitestnet"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "argparse>=1.4.0",
    "logging>=0.4.9.6",
    "python-binance>=1.0.29",
]
